import OfferInterest from './OfferInterest.jsx';
import OfferText from './OfferText.jsx';
import ApplicationContextFields, {APPLICATION_CONTEXT_LABELS} from './ApplicationContextFields.jsx';
import { readDraft, writeDraft, clearDraft, useDraftState, useUnsavedWarning } from '../hooks/useDraft.js';
import OfferEditor from './OfferEditor.jsx';
import { useEffect, useState } from 'react';
import { profileApi } from '../lib/profileApi.js';
import { APPLICATION_STATUSES, interviewCalendar, applicationNextStep, formatInterviewDate } from '../lib/applications.js';
import { formatDate, safeOfferUrl } from '../lib/jobs.js';
const labels={...APPLICATION_CONTEXT_LABELS,appliedAt:'datum reakce',status:'stav',notes:'poznámky',salaryExpectation:'mzda uvedená firmě',reactionDetails:'údaje o odeslané reakci',title:'název pozice',company:'firma',location:'lokalita',salary_raw:'mzda v inzerátu',url:'odkaz',raw_description:'text nabídky',contacts:'kontakty',tasks:'další kroky',interviews:'pohovory'};
const eventLabel=e=>e.kind==='offer_updated'?'Upravená nabídka: '+(e.payload.changes||[]).map(key=>labels[key]).join(', '):e.kind==='applied'?'Zaznamenána odeslaná reakce':e.kind==='application_removed'?'Zrušeno označení reakce':e.kind==='imported'?'Importováno z místní historie (datum reakce podle podkladů)':'Upraveno: '+(e.payload.changes||[]).map(key=>labels[key]).join(', ');
function calendar(event,offer){const blob=new Blob([interviewCalendar(event,offer)],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pohovor.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ApplicationDetail({profileId,offerId,onClose,onChanged}) {
  const [detail,setDetail]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [documentLibrary,setDocumentLibrary]=useState([]),[sentPreview,setSentPreview]=useState(null);
  const draftKey = 'application:' + profileId + ':' + offerId;
  const [restored, setRestored] = useState(false);
  const [draftRevision,setDraftRevision]=useState(0);
  const [task,setTask]=useDraftState(draftKey+':task',''),[due,setDue]=useDraftState(draftKey+':due','');
  const [contact,setContact]=useDraftState(draftKey+':contact',{name:'',role:'',email:'',phone:''});
  const [interview,setInterview]=useDraftState(draftKey+':interview',{at:'',round:'',duration:60,place:'',note:''});
  async function load(){setError('');setBusy(true);try{const result=await profileApi('/api/applications?offerId='+encodeURIComponent(offerId));setDetail(result);const stored=readDraft(draftKey);setDraft(stored?.application ? {...result.application,...stored.application} : result.application);setDraftRevision(stored?.revision ?? result.revision);setRestored(!!stored);}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{let alive=true;setDetail(null);setDraft(null);profileApi('/api/applications?offerId='+encodeURIComponent(offerId)).then(result=>{if(alive){setDetail(result);const stored=readDraft(draftKey);setDraftRevision(stored?.revision ?? result.revision);setDraft(stored?.application ? {...result.application,...stored.application} : result.application);if(stored){setRestored(true);if(stored.revision!==result.revision)setError('Mezitím se změnila uložená přihláška. Obnovený koncept porovnej s uloženými údaji, než změny potvrdíš.');}}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[profileId,offerId]);
  useEffect(()=>{let alive=true;profileApi('/api/documents?profileId='+encodeURIComponent(profileId)).then(result=>{if(alive)setDocumentLibrary(result.items||[]);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[profileId]);
  async function persist(application, message, pending = null, afterSave = () => {}) {
    if (busy) return;
    setBusy(true);setError('');setNotice('');
    try {
      const result=await profileApi('/api/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId,offerId,revision:draftRevision,application})});
      setDetail(result);setDraft(pending ? {...result.application,...pending} : result.application);
      clearDraft(draftKey);setDraftRevision(result.revision);setRestored(false);setNotice(message);afterSave();onChanged();
    } catch(e) {setError(e.message);} finally {setBusy(false);}
  }
  async function save(e){e.preventDefault();await persist(draft,'Přihláška uložená.');}
  async function commitField(key, value, message, afterSave) {
    if (busy) return;
    const next={...draft,[key]:value};
    const pending=Object.fromEntries(Object.entries(next).filter(([field,value])=>field!==key&&JSON.stringify(value)!==JSON.stringify(detail.application[field])));
    await persist({...detail.application,[key]:value},message,pending,afterSave);
  }
  async function openSentDocument(item){
    setBusy(true);setError('');
    try{
      const result=await profileApi('/api/documents?id='+encodeURIComponent(item.id)+'&snapshot=1&offerId='+encodeURIComponent(offerId)+'&profileId='+encodeURIComponent(profileId));
      const doc=result.document;
      if(doc.kind==='letter')setSentPreview({name:doc.name,text:doc.textContent});
      else{const raw=atob(doc.base64),bytes=Uint8Array.from(raw,char=>char.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:doc.contentType}));setSentPreview({name:doc.name,url});}
    }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  function closeSentPreview(){if(sentPreview?.url)URL.revokeObjectURL(sentPreview.url);setSentPreview(null);}
  const dirty = !!detail && !!draft && JSON.stringify(draft)!==JSON.stringify(detail.application);
  useUnsavedWarning(dirty);
  useEffect(() => { if (dirty) writeDraft(draftKey,{application:draft,revision:draftRevision}); else if (detail && draft) clearDraft(draftKey); }, [draft,dirty,draftKey,draftRevision]);
  const update=(key,value)=>setDraft({...draft,[key]:value});
  function addInterview(){const at=new Date(interview.at);if(!Number.isFinite(at.getTime()))return;commitField('interviews',[...draft.interviews,{...interview,id:crypto.randomUUID(),at:at.toISOString(),duration:Number(interview.duration),cancelled:false}],'Termín pohovoru uložen.',()=>setInterview({at:'',round:'',duration:60,place:'',note:''}));}
  const next = draft ? applicationNextStep(draft) : null;
  return <section aria-label="Detail přihlášky" className="mt-5 rounded-2xl border border-border-subtle bg-surface p-5">
    <div className="flex justify-between gap-3"><h2 className="font-display text-xl font-semibold">{detail?.offer.title||'Detail přihlášky'}</h2><button type="button" className="button-secondary" onClick={onClose} disabled={busy}>Zavřít detail</button></div>
    {detail&&<p className="mt-2 text-sm text-ink-secondary">{detail.offer.company} · {detail.offer.location||'Lokalita neuvedena'}</p>}
    {detail&&<OfferInterest profileId={profileId} offerId={offerId} interest={detail.interest} onSaved={interest=>{setDetail(previous=>({...previous,interest,state:{...previous.state,priority:interest.priority}}));onChanged();}} />}
    {error&&<div role="alert" className="mt-3 text-sm text-danger">{error}<button type="button" className="button-secondary ml-2" disabled={busy} onClick={load}>Načíst detail znovu</button></div>}
    {!draft&&!error&&<p role="status" className="mt-4">Načítám přihlášku…</p>}
    {draft&&<form onSubmit={save} className="mt-5 space-y-5"><fieldset disabled={busy} className="space-y-5">
      {restored && <p role="status" className="rounded-xl bg-surface-subtle p-3 text-sm">Obnovili jsme tvůj rozepsaný koncept v tomto prohlížeči. Zkontroluj ho a ulož změny.</p>}
      {dirty && <p role="status" className="rounded-xl bg-fit-potential-bg text-fit-potential-text p-3 text-sm">Koncept je uchovaný v této kartě prohlížeče. Do přihlášky ho uložíš tlačítkem Uložit změny.</p>}
      <section aria-label="Nejbližší krok" className="rounded-2xl border border-border-subtle bg-white p-4 sm:p-5">
        <p className="text-xs font-medium text-brand">{next.kind==='closed'?'Přihláška uzavřená':'Co teď udělat'}</p><h3 className="mt-2 text-lg font-semibold">{next.text}</h3>
        {next.at&&<p className="mt-2 text-sm">{formatInterviewDate(next.at)}</p>}{next.due&&<p className={'mt-2 text-sm '+(next.overdue?'text-danger':'text-ink-secondary')}>{next.overdue?'Po termínu · ':'Do '}{formatDate(next.due)}</p>}
        {next.daysSinceApplied!==null&&<p className="mt-2 text-xs text-ink-secondary">{next.daysSinceApplied} dní od odeslání reakce</p>}
        {next.suggestFollowUp&&<button type="button" className="button-secondary mt-3" onClick={()=>commitField('tasks',[...draft.tasks,{id:crypto.randomUUID(),text:'Připomenout se firmě',due:null,done:false}],'Další krok uložený.')}>Naplánovat připomenutí</button>}
        {next.suggestFollowUp&&<p className="mt-2 text-xs text-ink-secondary">Jen návrh dalšího kroku. Zprávu firmě odešleš sám.</p>}
      </section>
      <section aria-label="Rychlé zaznamenání pohovoru" className="rounded-2xl border border-border-subtle bg-surface-subtle p-4 sm:p-5">
        <h3 className="font-semibold">Přidat termín pohovoru</h3><p className="mt-1 text-xs text-ink-secondary">Uloží se hned po kliknutí. Čas se bere z časového pásma prohlížeče.</p>
        <div className="mt-3 grid gap-3 sm:grid-cols-[1fr_1fr_auto]">
          <label className="text-sm">Datum a čas<input type="datetime-local" value={interview.at} onChange={e=>setInterview({...interview,at:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label>
          <label className="text-sm">Kolo pohovoru<input value={interview.round} maxLength={200} onChange={e=>setInterview({...interview,round:e.target.value})} placeholder="Např. 1. kolo s HR" className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label>
          <button type="button" className="button-primary self-end" disabled={!interview.at||busy} onClick={addInterview}>Uložit termín</button>
        </div>
        <details className="mt-3"><summary className="cursor-pointer text-sm font-medium text-brand">Doplnit délku, místo a poznámku</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">Délka v minutách<input type="number" min={5} max={480} value={interview.duration} onChange={e=>setInterview({...interview,duration:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label><label className="text-sm">Místo / odkaz<input maxLength={1000} value={interview.place} onChange={e=>setInterview({...interview,place:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label><label className="text-sm sm:col-span-2">Poznámka<input maxLength={5000} value={interview.note} onChange={e=>setInterview({...interview,note:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label></div></details>
      </section>
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Stav<select value={draft.status} onChange={e=>commitField('status',e.target.value,'Změna stavu uložena.')} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3">{Object.entries(APPLICATION_STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><span role="status" className="mt-1 block text-xs text-brand">{notice==='Změna stavu uložena.'?notice:''}</span></label><label className="text-sm">Datum reakce (neznámé nech prázdné)<input type="date" value={draft.appliedAt||''} onChange={e=>update('appliedAt',e.target.value||null)} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label></div>

      <section aria-label="Další kroky"><h3 className="font-semibold">Další kroky</h3><p className="mt-1 text-xs text-ink-secondary">Přidání, dokončení i změna termínu se rovnou uloží.</p><ul className="mt-2 space-y-2">{draft.tasks.map(t=><li key={t.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-white p-3"><label className="flex flex-1 items-center gap-2 text-sm"><input type="checkbox" checked={t.done} onChange={e=>commitField('tasks',draft.tasks.map(item=>item.id===t.id?{...item,done:e.target.checked}:item),'Krok uložený.')} /><span className={t.done?'line-through text-ink-secondary':''}>{t.text}</span></label><label className="text-xs">Termín<input type="date" aria-label={'Termín kroku: '+t.text} value={t.due||''} onChange={e=>commitField('tasks',draft.tasks.map(item=>item.id===t.id?{...item,due:e.target.value||null}:item),'Termín uložený.')} className="ml-2 rounded-lg border border-border-subtle p-1 text-xs" /></label><button type="button" className="text-xs text-ink-secondary" onClick={()=>commitField('tasks',draft.tasks.filter(item=>item.id!==t.id),'Krok odebraný.')}>Odebrat</button></li>)}</ul>
        <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><label className="col-span-2 min-w-0 text-xs sm:col-span-1">Nový krok<input value={task} maxLength={1000} onChange={e=>setTask(e.target.value)} placeholder="Např. zavolat personalistovi" className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3 text-sm" /></label><label className="min-w-0 text-xs">Do kdy<input type="date" value={due} onChange={e=>setDue(e.target.value)} className="mt-1 block w-full min-w-0 rounded-xl border border-border-subtle bg-white p-3 text-sm" /></label><button type="button" className="button-secondary self-end" disabled={!task.trim()} onClick={()=>commitField('tasks',[...draft.tasks,{id:crypto.randomUUID(),text:task.trim(),due:due||null,done:false}],'Další krok uložený.',()=>{setTask('');setDue('');})}>Přidat krok</button></div></section>
      <section aria-label="Pohovory"><h3 className="font-semibold">Pohovory</h3><p className="mt-1 text-xs text-ink-secondary">Přidání a zrušení pohovoru se rovnou uloží. Do kalendáře ho přidáš samostatně.</p><ul className="mt-2 space-y-2">{draft.interviews.map(i=><li key={i.id} className="rounded-xl bg-white p-3 text-sm"><p>{new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Prague'}).format(new Date(i.at))}{i.round?' · '+i.round:''} · {i.duration} min {i.cancelled?'· Zrušeno':''}</p><p className="mt-1 whitespace-pre-wrap text-ink-secondary">{i.place} {i.note}</p><div className="mt-2 flex flex-wrap gap-3">{!i.cancelled&&<button type="button" className="text-xs font-medium text-brand" onClick={()=>calendar(i,detail.offer)}>Přidat do kalendáře</button>}<button type="button" className="text-xs text-ink-secondary" onClick={()=>commitField('interviews',draft.interviews.map(item=>item.id===i.id?{...item,cancelled:!item.cancelled}:item),'Pohovor uložený.')}>{i.cancelled?'Obnovit pohovor':'Zrušit pohovor'}</button></div></li>)}</ul>
      </section>
      <section aria-label="Plat sdělený firmě" className="rounded-xl border border-border-subtle bg-white p-4">
        <h3 className="text-sm font-semibold">Plat uvedený v reakci</h3>
        <label className="mt-3 block text-sm">Plat / rozmezí uvedené firmě
          <input value={draft.salaryExpectation||''} maxLength={1000} onChange={e=>update('salaryExpectation',e.target.value)} placeholder="Např. 70 000–80 000 Kč hrubého měsíčně" className="mt-1 w-full rounded-xl border border-border-subtle p-3" />
        </label>
        <p className="mt-2 text-xs text-ink-secondary">Uveď částku nebo rozmezí včetně měny a informace, zda jde o hrubou či čistou mzdu. Změnu uložíš tlačítkem „Uložit změny“.</p>
        <details className="mt-4 border-t border-border-subtle pt-3">
          <summary className="cursor-pointer text-sm font-medium text-brand">Další údaje o odeslané reakci</summary>
          <label className="mt-3 block text-sm">Další údaje o odeslané reakci
            <textarea value={draft.reactionDetails||''} maxLength={5000} rows={3} onChange={e=>update('reactionDetails',e.target.value)} placeholder="Jak jsem reagoval, co jsem napsal nebo odeslal…" className="mt-1 w-full rounded-xl border border-border-subtle p-3" />
          </label>
        </details>
      </section>
      <section aria-label="Dokumenty poslané firmě" className="rounded-xl border border-border-subtle bg-white p-4"><h3 className="text-sm font-semibold">Dokumenty poslané firmě</h3><p className="mt-1 text-xs leading-relaxed text-ink-secondary">Vyber přesné verze CV nebo motivačního dopisu. Po uložení zůstane u přihlášky kopie toho, co jsi poslal.</p>{documentLibrary.length?<div className="mt-3 grid gap-2 sm:grid-cols-2">{documentLibrary.map(item=><label key={item.id} className="flex min-h-11 items-center gap-3 rounded-xl border border-border-subtle bg-surface-subtle p-3 text-sm"><input type="checkbox" checked={(draft.sentDocumentIds||[]).includes(item.id)} onChange={event=>update('sentDocumentIds',event.target.checked?[...new Set([...(draft.sentDocumentIds||[]),item.id])]:(draft.sentDocumentIds||[]).filter(id=>id!==item.id))} className="h-4 w-4 accent-brand"/><span className="min-w-0"><span className="block break-words font-medium">{item.name}</span><span className="text-xs text-ink-secondary">{item.kind==='cv'?'Životopis':'Motivační dopis'}</span></span></label>)}</div>:<p className="mt-3 text-sm text-ink-secondary">Knihovna je zatím prázdná. Přidej dokument v sekci Dokumenty.</p>}{detail?.sentDocumentSnapshots?.length>0&&<div className="mt-4 border-t border-border-subtle pt-3"><p className="text-xs font-semibold text-ink-secondary">Uložené kopie přiřazených dokumentů</p><ul className="mt-2 space-y-2">{detail.sentDocumentSnapshots.map(item=><li key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-surface-subtle px-3 py-2 text-sm"><span>{item.name} <span className="text-xs text-ink-secondary">· {new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium'}).format(new Date(item.attachedAt))}</span></span><button type="button" className="button-secondary" disabled={busy} onClick={()=>openSentDocument(item)}>Zobrazit kopii</button></li>)}</ul></div>}</section>
      <ApplicationContextFields draft={draft} update={update} />
      <label className="block text-sm font-semibold">Poznámky<textarea rows={4} value={draft.notes} maxLength={20000} onChange={e=>update('notes',e.target.value)} className="mt-2 w-full rounded-xl border border-border-subtle bg-white p-3 text-sm font-normal" placeholder="Co firma odpověděla, co si připravit…" /></label>
      <details><summary className="cursor-pointer text-sm font-medium text-brand">Kontakty ({draft.contacts.length})</summary><ul className="mt-3 space-y-2">{draft.contacts.map(c=><li key={c.id} className="flex flex-wrap justify-between gap-2 rounded-xl bg-white p-3 text-sm"><div><p>{c.name} · {c.role}</p><p className="break-all text-ink-secondary">{c.email} {c.phone}</p></div><button type="button" className="text-xs text-ink-secondary" onClick={()=>commitField('contacts',draft.contacts.filter(item=>item.id!==c.id),'Kontakt odebraný.')}>Odebrat kontakt</button></li>)}</ul><div className="mt-3 grid gap-3 sm:grid-cols-2">{[['name','Jméno'],['role','Role'],['email','E-mail'],['phone','Telefon']].map(([key,label])=><label key={key} className="text-xs">{label}<input value={contact[key]} maxLength={key==='email'?320:200} onChange={e=>setContact({...contact,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3 text-sm" /></label>)}</div><button type="button" className="button-secondary mt-3" disabled={!contact.name.trim()} onClick={()=>commitField('contacts',[...draft.contacts,{...contact,id:crypto.randomUUID()}],'Kontakt uložený.',()=>setContact({name:'',role:'',email:'',phone:''}))}>Přidat kontakt</button></details>
      <div className={"flex flex-wrap items-center gap-3 rounded-2xl border border-border-subtle bg-surface-subtle p-3 " + (dirty ? "sticky bottom-3 z-10 shadow-soft" : "")}><button type="submit" className="button-primary" disabled={!dirty}>{busy?'Ukládám…':'Uložit změny'}</button><p role="status" className="text-sm text-brand">{(busy ? 'Ukládám…' : notice) || (dirty ? 'Neuložené změny' : 'Všechny změny uložené')}</p>{dirty && notice && <span className="text-xs text-ink-secondary">Ostatní rozepsané údaje čekají na uložení.</span>}{dirty && <button type="button" className="button-secondary" onClick={() => { setDraft(detail.application); setDraftRevision(detail.revision); clearDraft(draftKey); setRestored(false); }}>Zahodit koncept</button>}</div>
    </fieldset></form>}
    {detail&&<details className="mt-6 border-t border-border-subtle pt-4"><summary className="cursor-pointer text-sm font-medium text-brand">Historie událostí ({detail.events.length})</summary><ol className="mt-3 space-y-3">{detail.events.map(e=><li key={e.id} className="text-sm"><p className="text-xs text-ink-secondary">{new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Prague'}).format(new Date(e.at))}</p><p>{eventLabel(e)}</p>{e.payload.after?.status&&e.payload.before.status!==e.payload.after.status&&<p>{APPLICATION_STATUSES[e.payload.before.status]} → {APPLICATION_STATUSES[e.payload.after.status]}</p>}{['updated','offer_updated'].includes(e.kind)&&<details className="mt-1"><summary className="cursor-pointer text-xs text-ink-secondary">Obsah změny</summary><div className="mt-2 whitespace-pre-wrap text-xs">{(e.payload.changes||[]).filter(key=>key!=='status').map(key=><p key={key}>{labels[key]}: {typeof e.payload.after[key]==='string'?e.payload.after[key]:JSON.stringify(e.payload.after[key])}</p>)}</div></details>}</li>)}</ol>{!detail.events.length&&<p className="mt-3 text-sm text-ink-secondary">Starší reakce nemá známé datum ani historii. Doplň je podle svých podkladů.</p>}</details>}
    {detail&&<details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-brand">Upravit nabídku</summary><OfferEditor profileId={profileId} offerId={offerId} initialDetail={detail} onSaved={result=>{setDetail(previous=>({...previous,offer:result.offer,offerRevision:result.offerRevision,offerEdited:result.offerEdited,evaluationStale:result.evaluationStale,translation:result.translation,events:result.events}));onChanged();}} /></details>}
    {detail&&<details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-brand">Původní nabídka</summary>{safeOfferUrl(detail.offer.url)&&<a href={detail.offer.url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 items-center text-sm text-brand">Otevřít inzerát</a>}<OfferText key={offerId+":"+detail.offerRevision} profileId={profileId} offerId={offerId} text={detail.offer.raw_description} translation={detail.translation} /></details>}
    {sentPreview&&<div role="dialog" aria-modal="true" aria-label={'Odeslaný dokument: '+sentPreview.name} className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={closeSentPreview}><div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-border-subtle bg-surface" onClick={event=>event.stopPropagation()}><div className="flex items-center justify-between gap-3 border-b border-border-subtle p-4"><h2 className="truncate font-semibold">{sentPreview.name}</h2><button type="button" className="button-secondary" onClick={closeSentPreview}>Zavřít</button></div>{sentPreview.text!==undefined?<pre className="overflow-auto whitespace-pre-wrap p-5 text-sm leading-relaxed">{sentPreview.text}</pre>:<iframe title={'Náhled '+sentPreview.name} src={sentPreview.url} className="min-h-[65vh] w-full bg-white"/>}</div></div>}
  </section>;
}
