import OfferEditor from './OfferEditor.jsx';
import { useEffect, useState } from 'react';
import { profileApi } from '../lib/profileApi.js';
import { APPLICATION_STATUSES, interviewCalendar } from '../lib/applications.js';
import { formatDate, safeOfferUrl } from '../lib/jobs.js';
const labels={appliedAt:'datum reakce',status:'stav',notes:'poznámky',salaryExpectation:'mzda uvedená firmě',reactionDetails:'údaje o odeslané reakci',title:'název pozice',company:'firma',location:'lokalita',salary_raw:'mzda v inzerátu',url:'odkaz',raw_description:'text nabídky',contacts:'kontakty',tasks:'další kroky',interviews:'pohovory'};
const eventLabel=e=>e.kind==='offer_updated'?'Upravená nabídka: '+(e.payload.changes||[]).map(key=>labels[key]).join(', '):e.kind==='applied'?'Zaznamenána odeslaná reakce':e.kind==='application_removed'?'Zrušeno označení reakce':e.kind==='imported'?'Importováno z místní historie (datum reakce podle podkladů)':'Upraveno: '+(e.payload.changes||[]).map(key=>labels[key]).join(', ');
function calendar(event,offer){const blob=new Blob([interviewCalendar(event,offer)],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pohovor.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ApplicationDetail({profileId,offerId,onClose,onChanged}) {
  const [detail,setDetail]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [task,setTask]=useState(''),[due,setDue]=useState('');
  const [contact,setContact]=useState({name:'',role:'',email:'',phone:''});
  const [interview,setInterview]=useState({at:'',duration:60,place:'',note:''});
  async function load(){setError('');setBusy(true);try{const result=await profileApi('/api/applications?offerId='+encodeURIComponent(offerId));setDetail(result);setDraft(result.application);}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{let alive=true;setDetail(null);setDraft(null);profileApi('/api/applications?offerId='+encodeURIComponent(offerId)).then(result=>{if(alive){setDetail(result);setDraft(result.application);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[profileId,offerId]);
  async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await profileApi('/api/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId,offerId,revision:detail.revision,application:draft})});setDetail(result);setDraft(result.application);setNotice('Přihláška uložená.');onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const dirty = !!detail && !!draft && JSON.stringify(draft)!==JSON.stringify(detail.application);
  const update=(key,value)=>setDraft({...draft,[key]:value});
  function addInterview(){const at=new Date(interview.at);if(!Number.isFinite(at.getTime()))return;update('interviews',[...draft.interviews,{...interview,id:crypto.randomUUID(),at:at.toISOString(),duration:Number(interview.duration),cancelled:false}]);setInterview({at:'',duration:60,place:'',note:''});}
  return <section aria-label="Detail přihlášky" className="mt-5 rounded-2xl border border-viatix-line bg-viatix-sand2 p-5">
    <div className="flex justify-between gap-3"><h2 className="font-display text-xl font-semibold">{detail?.offer.title||'Detail přihlášky'}</h2><button type="button" className="button-secondary" onClick={onClose} disabled={busy}>Zavřít detail</button></div>
    {detail&&<p className="mt-2 text-sm text-muted-foreground">{detail.offer.company} · {detail.offer.location||'Lokalita neuvedena'}</p>}
    {error&&<div role="alert" className="mt-3 text-sm text-red-700">{error}<button type="button" className="button-secondary ml-2" disabled={busy} onClick={load}>Načíst detail znovu</button></div>}
    {!draft&&!error&&<p role="status" className="mt-4">Načítám přihlášku…</p>}
    {draft&&<form onSubmit={save} className="mt-5 space-y-5"><fieldset disabled={busy} className="space-y-5">
      {dirty && <p role="status" className="rounded-xl bg-viatix-amber/15 p-3 text-sm">Máš neuložené změny. Potvrď je tlačítkem Uložit změny.</p>}
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Stav<select value={draft.status} onChange={e=>update('status',e.target.value)} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3">{Object.entries(APPLICATION_STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="text-sm">Datum reakce (neznámé nech prázdné)<input type="date" value={draft.appliedAt||''} onChange={e=>update('appliedAt',e.target.value||null)} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3" /></label></div>
      <section aria-label="Moje odeslaná reakce" className="rounded-xl border border-viatix-line bg-white p-4"><h3 className="font-semibold">Co jsem uvedl v reakci</h3><label className="mt-3 block text-sm">Plat / rozmezí uvedené firmě<input value={draft.salaryExpectation||''} maxLength={1000} onChange={e=>update('salaryExpectation',e.target.value)} placeholder="Např. 70 000–80 000 Kč hrubého měsíčně" className="mt-1 w-full rounded-xl border border-viatix-line p-3" /></label><p className="mt-2 text-xs text-muted-foreground">Zapiš přesně částku či rozmezí z dotazníku, včetně měny, hrubého/čistého platu nebo bonusů.</p><label className="mt-4 block text-sm">Další údaje o odeslané reakci<textarea value={draft.reactionDetails||''} maxLength={5000} rows={3} onChange={e=>update('reactionDetails',e.target.value)} placeholder="Jak jsem reagoval, co jsem napsal nebo odeslal…" className="mt-1 w-full rounded-xl border border-viatix-line p-3" /></label></section>
      <section aria-label="Další kroky"><h3 className="font-semibold">Další kroky</h3><ul className="mt-2 space-y-2">{draft.tasks.map(t=><li key={t.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-white p-3"><label className="flex flex-1 items-center gap-2 text-sm"><input type="checkbox" checked={t.done} onChange={e=>update('tasks',draft.tasks.map(item=>item.id===t.id?{...item,done:e.target.checked}:item))} /><span className={t.done?'line-through text-muted-foreground':''}>{t.text}</span></label><label className="text-xs">Termín<input type="date" aria-label={'Termín kroku: '+t.text} value={t.due||''} onChange={e=>update('tasks',draft.tasks.map(item=>item.id===t.id?{...item,due:e.target.value||null}:item))} className="ml-2 rounded-lg border border-viatix-line p-1 text-xs" /></label><button type="button" className="text-xs text-muted-foreground" onClick={()=>update('tasks',draft.tasks.filter(item=>item.id!==t.id))}>Odebrat</button></li>)}</ul>
        <div className="mt-3 flex flex-wrap gap-2"><label className="flex-1 text-xs">Nový krok<input value={task} maxLength={1000} onChange={e=>setTask(e.target.value)} placeholder="Např. zavolat personalistovi" className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label><label className="text-xs">Do kdy<input type="date" value={due} onChange={e=>setDue(e.target.value)} className="mt-1 block rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label><button type="button" className="button-secondary self-end" disabled={!task.trim()} onClick={()=>{update('tasks',[...draft.tasks,{id:crypto.randomUUID(),text:task.trim(),due:due||null,done:false}]);setTask('');setDue('');}}>Přidat krok</button></div></section>
      <section aria-label="Pohovory"><h3 className="font-semibold">Pohovory</h3><ul className="mt-2 space-y-2">{draft.interviews.map(i=><li key={i.id} className="rounded-xl bg-white p-3 text-sm"><p>{new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Prague'}).format(new Date(i.at))} · {i.duration} min {i.cancelled?'· Zrušeno':''}</p><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{i.place} {i.note}</p><div className="mt-2 flex flex-wrap gap-3">{!i.cancelled&&<button type="button" className="text-xs font-medium text-viatix-teal" onClick={()=>calendar(i,detail.offer)}>Přidat do kalendáře</button>}<button type="button" className="text-xs text-muted-foreground" onClick={()=>update('interviews',draft.interviews.map(item=>item.id===i.id?{...item,cancelled:!item.cancelled}:item))}>{i.cancelled?'Obnovit pohovor':'Zrušit pohovor'}</button></div></li>)}</ul>
        <details className="mt-3"><summary className="cursor-pointer text-sm font-medium text-viatix-teal">Přidat termín pohovoru</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs">Datum a čas (časové pásmo prohlížeče)<input type="datetime-local" value={interview.at} onChange={e=>setInterview({...interview,at:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label><label className="text-xs">Délka v minutách<input type="number" min={5} max={480} value={interview.duration} onChange={e=>setInterview({...interview,duration:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label><label className="text-xs">Místo / odkaz<input maxLength={1000} value={interview.place} onChange={e=>setInterview({...interview,place:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label><label className="text-xs">Poznámka<input maxLength={5000} value={interview.note} onChange={e=>setInterview({...interview,note:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label></div><button type="button" className="button-secondary mt-3" disabled={!interview.at} onClick={addInterview}>Přidat pohovor</button></details></section>
      <label className="block text-sm font-semibold">Poznámky<textarea rows={4} value={draft.notes} maxLength={20000} onChange={e=>update('notes',e.target.value)} className="mt-2 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm font-normal" placeholder="Co firma odpověděla, co si připravit…" /></label>
      <details><summary className="cursor-pointer text-sm font-medium text-viatix-teal">Kontakty ({draft.contacts.length})</summary><ul className="mt-3 space-y-2">{draft.contacts.map(c=><li key={c.id} className="flex flex-wrap justify-between gap-2 rounded-xl bg-white p-3 text-sm"><div><p>{c.name} · {c.role}</p><p className="break-all text-muted-foreground">{c.email} {c.phone}</p></div><button type="button" className="text-xs text-muted-foreground" onClick={()=>update('contacts',draft.contacts.filter(item=>item.id!==c.id))}>Odebrat kontakt</button></li>)}</ul><div className="mt-3 grid gap-3 sm:grid-cols-2">{[['name','Jméno'],['role','Role'],['email','E-mail'],['phone','Telefon']].map(([key,label])=><label key={key} className="text-xs">{label}<input value={contact[key]} maxLength={key==='email'?320:200} onChange={e=>setContact({...contact,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3 text-sm" /></label>)}</div><button type="button" className="button-secondary mt-3" disabled={!contact.name.trim()} onClick={()=>{update('contacts',[...draft.contacts,{...contact,id:crypto.randomUUID()}]);setContact({name:'',role:'',email:'',phone:''});}}>Přidat kontakt</button></details>
      <div className="flex flex-wrap items-center gap-3"><button type="submit" className="button-primary">{busy?'Ukládám…':'Uložit změny'}</button><p role="status" className="text-sm text-viatix-teal">{notice}</p></div>
    </fieldset></form>}
    {detail&&<details className="mt-6 border-t border-viatix-line pt-4"><summary className="cursor-pointer text-sm font-medium text-viatix-teal">Historie událostí ({detail.events.length})</summary><ol className="mt-3 space-y-3">{detail.events.map(e=><li key={e.id} className="text-sm"><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Prague'}).format(new Date(e.at))}</p><p>{eventLabel(e)}</p>{e.payload.after?.status&&e.payload.before.status!==e.payload.after.status&&<p>{APPLICATION_STATUSES[e.payload.before.status]} → {APPLICATION_STATUSES[e.payload.after.status]}</p>}{['updated','offer_updated'].includes(e.kind)&&<details className="mt-1"><summary className="cursor-pointer text-xs text-muted-foreground">Obsah změny</summary><div className="mt-2 whitespace-pre-wrap text-xs">{(e.payload.changes||[]).filter(key=>key!=='status').map(key=><p key={key}>{labels[key]}: {typeof e.payload.after[key]==='string'?e.payload.after[key]:JSON.stringify(e.payload.after[key])}</p>)}</div></details>}</li>)}</ol>{!detail.events.length&&<p className="mt-3 text-sm text-muted-foreground">Starší reakce nemá známé datum ani historii. Doplň je podle svých podkladů.</p>}</details>}
    {detail&&<details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-viatix-teal">Upravit nabídku</summary><OfferEditor profileId={profileId} offerId={offerId} initialDetail={detail} onSaved={result=>{setDetail(previous=>({...previous,offer:result.offer,offerRevision:result.offerRevision,offerEdited:result.offerEdited,evaluationStale:result.evaluationStale,events:result.events}));onChanged();}} /></details>}
    {detail&&<details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-viatix-teal">Původní nabídka</summary>{safeOfferUrl(detail.offer.url)&&<a href={detail.offer.url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-sm text-viatix-teal">Otevřít inzerát</a>}<p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{detail.offer.raw_description||'Text nabídky nebyl doplněn.'}</p></details>}
  </section>;
}
