import { useEffect, useState } from 'react';
import { Download, Eye, FileText, Loader2, Mail, Trash2, Upload, X } from 'lucide-react';
import { profileApi } from '../lib/profileApi.js';

const accepted='.pdf,.docx,.txt,.md';
function mime(name){const ext=name.split('.').pop().toLowerCase();return({pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',txt:'text/plain',md:'text/markdown'})[ext]||'application/octet-stream';}
function blobFrom(doc){const raw=atob(doc.base64),bytes=Uint8Array.from(raw,char=>char.charCodeAt(0));return new Blob([bytes],{type:doc.contentType||mime(doc.name)});}
async function encode(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});}

export default function DocumentsPanel({profileId}){
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [title,setTitle]=useState(''),[text,setText]=useState(''),[preview,setPreview]=useState(null);
  async function load(){setLoading(true);setError('');try{const result=await profileApi('/api/documents?profileId='+encodeURIComponent(profileId));setItems(result.items||[]);}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{setItems([]);load();},[profileId]);
  function closePreview(){if(preview?.url)URL.revokeObjectURL(preview.url);setPreview(null);}
  async function addCv(file){if(!file)return;setBusy(true);setError('');setNotice('');try{if(file.size>2_000_000||! /\.(pdf|docx|txt|md)$/i.test(file.name))throw new Error('Vyber PDF, DOCX, TXT nebo Markdown do 2 MB.');const result=await profileApi('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId,kind:'cv',name:file.name,base64:await encode(file)})},120000);setItems(current=>[result.document,...current]);setNotice('Životopis byl přidán do Dokumentů.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function addLetter(event){event.preventDefault();if(!title.trim()||!text.trim())return;setBusy(true);setError('');setNotice('');try{const result=await profileApi('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId,kind:'letter',name:title.trim(),textContent:text})});setItems(current=>[result.document,...current]);setTitle('');setText('');setNotice('Motivační dopis byl uložen.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function show(item){setBusy(true);setError('');try{const result=await profileApi('/api/documents?id='+encodeURIComponent(item.id)+'&download=1&profileId='+encodeURIComponent(profileId));if(item.kind==='letter')setPreview({item,content:result.document.textContent});else setPreview({item,url:URL.createObjectURL(blobFrom(result.document))});}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function download(item){setBusy(true);setError('');try{const result=await profileApi('/api/documents?id='+encodeURIComponent(item.id)+'&download=1&profileId='+encodeURIComponent(profileId));if(item.kind==='letter'){const url=URL.createObjectURL(new Blob([result.document.textContent],{type:'text/plain;charset=utf-8'}));const a=window.document.createElement('a');a.href=url;a.download=item.name.replace(/[^\p{L}\p{N} _.-]/gu,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else{const url=URL.createObjectURL(blobFrom(result.document));const a=window.document.createElement('a');a.href=url;a.download=item.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function remove(item){if(!window.confirm('Smazat „'+item.name+'“ z knihovny Dokumenty? Již uložené kopie u přihlášek zůstanou zachované.'))return;setBusy(true);setError('');try{await profileApi('/api/documents?id='+encodeURIComponent(item.id)+'&profileId='+encodeURIComponent(profileId),{method:'DELETE'});setItems(current=>current.filter(doc=>doc.id!==item.id));if(preview?.item.id===item.id)closePreview();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function assignEverywhere(item){setBusy(true);setError('');setNotice('');try{const result=await profileApi('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'assign-cv-to-applications',documentId:item.id})});setNotice('CV bylo přiřazeno k '+result.assigned+' uloženým přihláškám.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section aria-label="Dokumenty" className="mt-6 space-y-5">
    <div className="rounded-2xl border border-border-subtle bg-surface p-5 sm:p-6"><div className="flex items-start gap-3"><FileText className="mt-1 h-5 w-5 text-brand" aria-hidden="true"/><div><h2 className="font-display text-xl font-semibold">Knihovna dokumentů</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-ink-secondary">Ulož si různé verze životopisu a texty motivačních dopisů. V detailu přihlášky pak označíš přesně ty podklady, které jsi firmě poslal.</p></div></div>
      <div className="mt-5 flex flex-wrap items-center gap-3"><label className="button-primary cursor-pointer"><Upload className="h-4 w-4" aria-hidden="true"/>Nahrát CV<input type="file" accept={accepted} disabled={busy} className="sr-only" onChange={event=>{const file=event.target.files?.[0];event.target.value='';addCv(file);}}/></label><span className="text-xs text-ink-secondary">PDF, DOCX, TXT nebo MD · do 2 MB</span></div>
      <p className="mt-3 rounded-xl bg-fit-potential-bg p-3 text-xs leading-relaxed text-fit-potential-text">Tato prototypová verze má společné přihlášení. Dokumenty a jejich kopie u přihlášek jsou proto dostupné všem přihlášeným uživatelům.</p>
      <form onSubmit={addLetter} className="mt-6 rounded-xl border border-border-subtle bg-surface-subtle p-4"><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-brand" aria-hidden="true"/><h3 className="text-sm font-semibold">Nový motivační dopis</h3></div><label className="mt-3 block text-sm">Název<input value={title} maxLength={180} onChange={event=>setTitle(event.target.value)} placeholder="Např. Produktový designér · česká verze" className="mt-1 min-h-11 w-full rounded-xl border border-border-subtle bg-white p-3"/></label><label className="mt-3 block text-sm">Text dopisu<textarea value={text} maxLength={20000} rows={7} onChange={event=>setText(event.target.value)} placeholder="Vlož nebo napiš text motivačního dopisu…" className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3 leading-relaxed"/></label><button type="submit" disabled={busy||!title.trim()||!text.trim()} className="button-secondary mt-3">Uložit dopis</button></form>
    </div>
    {notice&&<p role="status" className="rounded-xl bg-fit-strong-bg p-3 text-sm text-fit-strong-text">{notice}</p>}{error&&<p role="alert" className="rounded-xl bg-fit-low-bg p-3 text-sm text-fit-low-text">{error}</p>}
    <section aria-label="Uložené dokumenty" className="rounded-2xl border border-border-subtle bg-surface p-5 sm:p-6"><h2 className="font-display text-lg font-semibold">Uložené dokumenty</h2>{loading?<p role="status" className="mt-4 text-sm text-ink-secondary">Načítám dokumenty…</p>:items.length?<ul className="mt-4 divide-y divide-border-subtle">{items.map(item=><li key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4 first:pt-0 last:pb-0"><div className="flex min-w-0 items-start gap-3"><div className="mt-1 rounded-lg bg-surface-subtle p-2 text-brand">{item.kind==='letter'?<Mail className="h-4 w-4" aria-hidden="true"/>:<FileText className="h-4 w-4" aria-hidden="true"/>}</div><div className="min-w-0"><p className="break-words text-sm font-semibold">{item.name}</p><p className="mt-1 text-xs text-ink-secondary">{item.kind==='letter'?'Motivační dopis · text':`Životopis · ${(item.size/1024).toFixed(0)} kB`} · {new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium'}).format(new Date(item.createdAt))}</p></div></div><div className="flex flex-wrap gap-2">{item.kind==='cv'&&<button type="button" className="button-secondary" disabled={busy} onClick={()=>assignEverywhere(item)}>Přiřadit ke všem přihláškám</button>}<button type="button" className="button-secondary" disabled={busy} onClick={()=>show(item)}><Eye className="h-4 w-4" aria-hidden="true"/>Zobrazit</button><button type="button" className="button-secondary" disabled={busy} onClick={()=>download(item)}><Download className="h-4 w-4" aria-hidden="true"/>Stáhnout</button><button type="button" className="button-secondary text-danger" disabled={busy} aria-label={'Smazat '+item.name} onClick={()=>remove(item)}><Trash2 className="h-4 w-4" aria-hidden="true"/></button></div></li>)}</ul>:<p className="mt-3 text-sm leading-relaxed text-ink-secondary">Zatím tu nejsou žádné dokumenty. Nahraj CV a přidej případné motivační dopisy.</p>}</section>
    {preview&&<div role="dialog" aria-modal="true" aria-label={'Náhled: '+preview.item.name} className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={closePreview}><div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-border-subtle bg-surface shadow-popover" onClick={event=>event.stopPropagation()}><div className="flex items-center justify-between gap-3 border-b border-border-subtle p-4"><h2 className="truncate font-semibold">{preview.item.name}</h2><button type="button" className="button-secondary" onClick={closePreview}><X className="h-4 w-4" aria-hidden="true"/>Zavřít</button></div>{preview.content!==undefined?<pre className="overflow-auto whitespace-pre-wrap p-5 text-sm leading-relaxed">{preview.content}</pre>:<iframe title={'Náhled '+preview.item.name} src={preview.url} className="min-h-[65vh] w-full bg-white"/>}</div></div>}
    {busy&&<p role="status" className="fixed bottom-4 right-4 z-40 inline-flex items-center gap-2 rounded-xl border border-border-subtle bg-white px-4 py-3 text-sm shadow-soft"><Loader2 className="h-4 w-4 animate-spin" aria-hidden="true"/>Pracuji s dokumentem…</p>}
  </section>;
}
