import {readDraft,writeDraft,clearDraft,useUnsavedWarning} from '../hooks/useDraft.js';
import {useEffect,useRef,useState} from 'react';
import {profileApi} from '../lib/profileApi.js';
const fields=[['title','Název pozice'],['company','Firma'],['location','Lokalita'],['salary_raw','Mzda uvedená v inzerátu'],['url','Odkaz na nabídku']];
const formOffer=offer=>Object.fromEntries([...fields.map(([key])=>key),'raw_description'].map(key=>[key,offer[key]||'']));
export default function OfferEditor({profileId,offerId,initialDetail,onSaved,onClose,focusDescription=false}){
  const draftKey='offer:'+profileId+':'+offerId;
  const [detail,setDetail]=useState(initialDetail||null),[draft,setDraft]=useState(()=>readDraft(draftKey)?.offer || (initialDetail?formOffer(initialDetail.offer):null)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [draftRevision,setDraftRevision]=useState(()=>readDraft(draftKey)?.revision ?? initialDetail?.offerRevision ?? 0);
  const descriptionRef=useRef(null);
  useEffect(()=>{if(focusDescription)descriptionRef.current?.focus();},[focusDescription]);
  async function load(){setBusy(true);setError('');try{const result=await profileApi('/api/applications?offerId='+encodeURIComponent(offerId));setDetail(result);const stored=readDraft(draftKey);setDraft(stored?.offer || formOffer(result.offer));setDraftRevision(stored?.revision ?? result.offerRevision ?? 0);}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{if(initialDetail)return;let alive=true;profileApi('/api/applications?offerId='+encodeURIComponent(offerId)).then(result=>{if(alive){setDetail(result);setDraft(readDraft(draftKey)?.offer || formOffer(result.offer));setDraftRevision(readDraft(draftKey)?.revision ?? result.offerRevision ?? 0);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[profileId,offerId]);
  async function save(){setBusy(true);setError('');setNotice('');try{const result=await profileApi('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'editOffer',profileId,offerId,offerRevision:draftRevision,offer:draft})});setDetail(result);setDraft(formOffer(result.offer));clearDraft(draftKey);setDraftRevision(result.offerRevision||0);setNotice('Údaje nabídky uložené.');onSaved?.(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const dirty=!!draft && !!detail && JSON.stringify(draft)!==JSON.stringify(formOffer(detail.offer));
  useUnsavedWarning(dirty);
  useEffect(()=>{if(dirty)writeDraft(draftKey,{offer:draft,revision:draftRevision});},[draft,dirty,draftKey,draftRevision]);
  return <section aria-label="Úprava nabídky" className="mt-4 rounded-xl border border-border-subtle bg-surface p-4"><div className="flex justify-between gap-2"><h3 className="font-semibold">Upravit údaje nabídky</h3>{onClose&&<button type="button" onClick={onClose} disabled={busy} className="button-secondary">Zavřít úpravu</button>}</div>
    {!draft&&!error&&<p role="status" className="mt-3 text-sm">Načítám nabídku…</p>}
    {dirty&&<p role="status" className="mt-3 text-xs text-fit-potential-text">Koncept je uchovaný v této kartě prohlížeče. Údaje potvrď uložením.</p>}{draft&&<fieldset disabled={busy} className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-sm">{label}<input value={draft[key]} type={key==='url'?'url':'text'} maxLength={key==='url'?2000:300} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label>)}</div><label className="block text-sm">Text nabídky<textarea ref={descriptionRef} rows={5} value={draft.raw_description} maxLength={30000} onChange={e=>setDraft({...draft,raw_description:e.target.value})} className="mt-1 w-full rounded-xl border border-border-subtle bg-white p-3" /></label>{detail.evaluation&&<p className="text-xs text-ink-secondary">Původní AI hodnocení zůstane zachované a vychází z textu v době hodnocení.</p>}<button type="button" onClick={save} className="button-primary">{busy?'Ukládám…':'Uložit údaje nabídky'}</button>{dirty&&<button type="button" className="button-secondary ml-2" onClick={()=>{setDraft(formOffer(detail.offer));setDraftRevision(detail.offerRevision||0);clearDraft(draftKey);}}>Zahodit koncept</button>}</fieldset>}
    {error&&<div role="alert" className="mt-3 text-sm text-danger">{error}<button type="button" className="button-secondary ml-2" onClick={load} disabled={busy}>Načíst nabídku znovu</button></div>}{notice&&<p role="status" className="mt-3 text-sm text-brand">{notice}</p>}
  </section>;
}
