import {useEffect,useState} from 'react';
import {profileApi} from '../lib/profileApi.js';
const fields=[['title','Název pozice'],['company','Firma'],['location','Lokalita'],['salary_raw','Mzda uvedená v inzerátu'],['url','Odkaz na nabídku']];
const formOffer=offer=>Object.fromEntries([...fields.map(([key])=>key),'raw_description'].map(key=>[key,offer[key]||'']));
export default function OfferEditor({profileId,offerId,initialDetail,onSaved,onClose}){
  const [detail,setDetail]=useState(initialDetail||null),[draft,setDraft]=useState(initialDetail?formOffer(initialDetail.offer):null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function load(){setBusy(true);setError('');try{const result=await profileApi('/api/applications?offerId='+encodeURIComponent(offerId));setDetail(result);setDraft(formOffer(result.offer));}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{if(initialDetail)return;let alive=true;profileApi('/api/applications?offerId='+encodeURIComponent(offerId)).then(result=>{if(alive){setDetail(result);setDraft(formOffer(result.offer));}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[profileId,offerId]);
  async function save(){setBusy(true);setError('');setNotice('');try{const result=await profileApi('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'editOffer',profileId,offerId,offerRevision:detail.offerRevision||0,offer:draft})});setDetail(result);setDraft(formOffer(result.offer));setNotice('Údaje nabídky uložené.');onSaved?.(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section aria-label="Úprava nabídky" className="mt-4 rounded-xl border border-viatix-line bg-viatix-sand2 p-4"><div className="flex justify-between gap-2"><h3 className="font-semibold">Upravit údaje nabídky</h3>{onClose&&<button type="button" onClick={onClose} disabled={busy} className="button-secondary">Zavřít úpravu</button>}</div>
    {!draft&&!error&&<p role="status" className="mt-3 text-sm">Načítám nabídku…</p>}
    {draft&&<fieldset disabled={busy} className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-sm">{label}<input value={draft[key]} type={key==='url'?'url':'text'} maxLength={key==='url'?2000:300} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3" /></label>)}</div><label className="block text-sm">Text nabídky<textarea rows={5} value={draft.raw_description} maxLength={30000} onChange={e=>setDraft({...draft,raw_description:e.target.value})} className="mt-1 w-full rounded-xl border border-viatix-line bg-white p-3" /></label>{detail.evaluation&&<p className="text-xs text-muted-foreground">Původní AI hodnocení zůstane zachované a vychází z textu v době hodnocení.</p>}<button type="button" onClick={save} className="button-primary">{busy?'Ukládám…':'Uložit údaje nabídky'}</button></fieldset>}
    {error&&<div role="alert" className="mt-3 text-sm text-red-700">{error}<button type="button" className="button-secondary ml-2" onClick={load} disabled={busy}>Načíst nabídku znovu</button></div>}{notice&&<p role="status" className="mt-3 text-sm text-viatix-teal">{notice}</p>}
  </section>;
}
