import test from 'node:test';
import https from 'node:https';
import {Readable} from 'node:stream';
import {EventEmitter} from 'node:events';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {createClient} from '@libsql/client';
import {CloudStore} from './cloudStore.js';
import {profileTable} from './cloudProfile.js';
import {applicationDetail,updateApplication,listApplications,validateApplication,blankApplication} from './applicationStore.js';
import {addOffer,previewOffer,parseOfferHtml,canonicalId,publicAddress} from './externalOffer.js';
import {opportunityHistory,opportunityRequest} from './opportunityApi.js';
import {historyQuery} from './historyQuery.js';
import {decodeJobRows} from '../src/lib/jobs.js';
import {applicationSummary,interviewCalendar} from '../src/lib/applications.js';
import {importSnapshot,migrateLocalData} from './sharedMigration.js';
const content=await readFile(new URL('../public/templates/candidate-profile-template.json',import.meta.url),'utf8');
const offer={title:'Procesní specialista',company:'Firma s.r.o.',location:'Brno',salary_raw:'',raw_description:'Práce s procesy',url:'https://example.com/job?utm_source=mail'};
const evaluation={score:85,verdict:'STRONG_FIT',fit_reasons:['Důvod 1','Důvod 2'],gap_analysis:[],tailored_cv_highlights:[]};
test('canonical identity retains seniority and technology while removing administrative parentheses',()=>{
  const qualifiers=['Junior','Senior','Medior','Lead','Principal','Intern','Trainee','Head of','Python','React','DevOps'];
  const ids=new Set(qualifiers.map(q=>canonicalId('Acme',`Engineer (${q})`,'Praha')));
  assert.equal(ids.size,qualifiers.length);
  assert.ok(!ids.has(canonicalId('Acme','Engineer','Praha')));
  for(const noise of ['m/ž','m/f','dpp','hpp','ičo','plný úvazek','vhodné pro absolventy']){
    assert.equal(canonicalId('Acme',`Engineer (${noise})`,'Praha'),canonicalId('Acme','Engineer','Praha'));
    assert.equal(canonicalId('Acme',`Engineer (Senior Python ${noise})`,'Praha'),canonicalId('Acme','Engineer (Senior Python)','Praha'));
  }
});
async function setup(t){const client=createClient({url:'file::memory:'});t.after(()=>client.close());const store=new CloudStore(client,{now:()=>new Date('2026-10-09T10:00:00Z')});await store.initialize();const profile=await store.saveProfile({name:'Mine',content});return {store,client,profileId:profile.id};}
async function add(store,profileId,applied=true){return addOffer(store,{profileId,offer,applied,appliedAt:'2026-10-01'});}
test('manual offers need no tokens and persist without invented scores, URL or description',async t=>{const {store,profileId}=await setup(t);const saved=await addOffer(store,{profileId,offer:{...offer,url:'',raw_description:''},applied:false});const page=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&collection=saved'));assert.equal(page.total,1);const job=decodeJobRows(page.rows).jobs[0];assert.equal(job.evaluation,null);assert.equal(job.offer.url,null);assert.equal(job.offer.raw_description,'');assert.equal(job.state.saved,true);assert.equal(saved.duplicate,false);await assert.rejects(store.evaluateOffer({profileId,offerId:saved.offerId}),e=>e.status===400);});
test('confirmed delete removes an automatic offer, linked records, and its queued AI snapshot',async t=>{
 const {store,client,profileId}=await setup(t);const offerId='automatic-offer',table=profileTable(profileId);const automaticOffer={...offer,id:offerId,canonical_id:canonicalId(offer.company,offer.title,offer.location)};
 await client.execute({sql:`CREATE TABLE ${table} (offer_id TEXT PRIMARY KEY,offer TEXT,evaluation TEXT,evaluated_at TEXT)`});
 await client.execute({sql:`INSERT INTO ${table}(offer_id,offer) VALUES(?,?)`,args:[offerId,JSON.stringify(automaticOffer)]});
 const saved={offerId};
 await store.updateJobState({profileId,offerId:saved.offerId,changes:{saved:true}});
 await opportunityRequest(store,'POST','/api/applications',{action:'interest',profileId,offerId:saved.offerId,revision:0,priority:true,reason:'keep this reason'});
 await client.execute({sql:'INSERT INTO makai_offer_translations(profile_id,offer_id,source_hash,status,text) VALUES(?,?,?,?,?)',args:[profileId,saved.offerId,'hash','done','translated']});
 await client.execute({sql:'INSERT INTO makai_offer_edits(profile_id,offer_id,payload,revision) VALUES(?,?,?,?)',args:[profileId,saved.offerId,'{}',1]});
 await client.execute({sql:'INSERT INTO makai_offer_evaluation_versions(profile_id,offer_id,offer_revision) VALUES(?,?,?)',args:[profileId,saved.offerId,1]});
 await store.evaluateOffer({profileId,offerId:saved.offerId});
 const removed=await opportunityRequest(store,'POST','/api/applications',{action:'delete',profileId,offerId:saved.offerId});
 assert.deepEqual(removed,{deleted:true,offerId:saved.offerId,manual:false});
 await assert.rejects(applicationDetail(store,profileId,saved.offerId),e=>e.status===404);
 for(const table of ['makai_job_states','makai_offer_interest','makai_offer_translations','makai_offer_evaluation_versions','makai_offer_edits','makai_applications','makai_application_events','makai_manual_offers']){
   assert.equal((await client.execute({sql:`SELECT COUNT(*) AS n FROM ${table} WHERE profile_id=? AND offer_id=?`,args:[profileId,saved.offerId]})).rows[0].n,0,table);
 }
 assert.equal((await client.execute({sql:`SELECT COUNT(*) AS n FROM ${table} WHERE offer_id=?`,args:[saved.offerId]})).rows[0].n,0);
 assert.equal((await client.execute({sql:'SELECT COUNT(*) AS n FROM makai_runs WHERE profile_id=?',args:[profileId]})).rows[0].n,0);
 await assert.rejects(opportunityRequest(store,'POST','/api/applications',{action:'delete',profileId,offerId:saved.offerId}),e=>e.status===404);
});
test('confirmed delete removes a manually imported offer too',async t=>{
 const {store,profileId}=await setup(t);const saved=await addOffer(store,{profileId,offer,applied:false});
 const removed=await opportunityRequest(store,'POST','/api/applications',{action:'delete',profileId,offerId:saved.offerId});
 assert.equal(removed.manual,true);assert.equal((await store.client.execute({sql:'SELECT COUNT(*) AS n FROM makai_manual_offers WHERE profile_id=? AND offer_id=?',args:[profileId,saved.offerId]})).rows[0].n,0);
});
test('application changes, events and independent states survive a new server without altering original evaluation',async t=>{const {store,client,profileId}=await setup(t);const saved=await add(store,profileId);let detail=await applicationDetail(store,profileId,saved.offerId);assert.equal(detail.application.appliedAt,'2026-10-01');const changed={...detail.application,status:'interview',notes:'Firma odpověděla',contacts:[{name:'Eva',role:'HR',email:'eva@example.com',phone:''}],tasks:[{text:'Poslat CV',due:'2026-10-10',done:false}],interviews:[{at:'2026-10-12T10:00:00+02:00',duration:60,place:'Online',note:'Připravit ukázku',cancelled:false}]};detail=await updateApplication(store,{profileId,offerId:saved.offerId,revision:0,application:changed});assert.equal(detail.revision,1);assert.equal(detail.events.length,2);assert.equal(detail.application.interviews[0].at,'2026-10-12T08:00:00.000Z');const another=new CloudStore(client);assert.deepEqual((await applicationDetail(another,profileId,saved.offerId)).application,detail.application);await assert.rejects(updateApplication(another,{profileId,offerId:saved.offerId,revision:0,application:changed}),e=>e.status===409);assert.equal((await applicationDetail(store,profileId,saved.offerId)).events.length,2);await store.updateJobState({profileId,offerId:saved.offerId,changes:{hidden:true}});assert.equal((await listApplications(store,profileId)).items.length,1);await store.updateJobState({profileId,offerId:saved.offerId,changes:{applied:false}});assert.equal((await listApplications(store,profileId)).items.length,0);await store.updateJobState({profileId,offerId:saved.offerId,changes:{applied:true}});assert.deepEqual((await applicationDetail(store,profileId,saved.offerId)).application,detail.application);});
test('invalid date, duplicate IDs, missing timezones and malformed fields fail without any write',async t=>{const {store,profileId}=await setup(t);const saved=await add(store,profileId);const original=(await applicationDetail(store,profileId,saved.offerId));for(const application of [{...original.application,appliedAt:'2026-02-30'},{...original.application,status:'invented'},{...original.application,tasks:[{id:'same',text:'a',due:null,done:false},{id:'same',text:'b',due:null,done:false}]},{...original.application,interviews:[{at:'2026-10-12T10:00',duration:60,place:'',note:'',cancelled:false}]}])await assert.rejects(updateApplication(store,{profileId,offerId:saved.offerId,revision:0,application}));assert.deepEqual(await applicationDetail(store,profileId,saved.offerId),original);});
test('deduplication checks tracking-free URLs, source URLs and canonical identities before creating applications',async t=>{const {store,profileId}=await setup(t);const saved=await add(store,profileId);const duplicate=await addOffer(store,{profileId,offer:{...offer,url:'https://example.com/job?utm_campaign=new',title:'Different'},applied:true});assert.equal(duplicate.duplicate,true);assert.equal(duplicate.offerId,saved.offerId);const identity=await addOffer(store,{profileId,offer:{...offer,url:'https://other.example/job',company:'FIRMA',title:'Procesni specialista (m/ž) (HPP)'},applied:false});assert.equal(identity.duplicate,true);assert.equal((await listApplications(store,profileId)).items.length,1);});
test('reimport refreshes an unedited incomplete manual snapshot for the same URL',async t=>{const {store,profileId}=await setup(t);const url='https://notino.jobs.cz/detail-pozice?id=2001374025';const original=await addOffer(store,{profileId,offer:{...offer,title:'Process Improvement Specialist',company:'Notino',location:'Praha',raw_description:'Proč Notino Volné pozice Kontakty EN',url},applied:false});const refreshed=await addOffer(store,{profileId,offer:{...offer,title:'Process Improvement Specialist',company:'Notino s.r.o.',location:'Rajhrad, Jihomoravský kraj',raw_description:'Full Notino job description '.repeat(100),url},applied:false});assert.equal(refreshed.duplicate,false);assert.equal(refreshed.updated,true);assert.equal(refreshed.offerId,original.offerId);const detail=await applicationDetail(store,profileId,original.offerId);assert.equal(detail.offer.company,'Notino s.r.o.');assert.match(detail.offer.location,/Rajhrad/);assert.ok(detail.offer.raw_description.length>2000);assert.equal(detail.evaluation,null);});
test('legacy applied flag keeps unknown dates and manual imports repeat without overwriting edited data or undo',async t=>{const {store,client,profileId}=await setup(t);const snapshot={name:'Mine',content,selected:true,applications:[{employer:'Air Bank',position:'AI Engineer',reported_status:'applied',applied_at:null,notes:'Historická reakce'},{employer:'ABB',position:'Trainee',reported_status:'unknown'}]};await importSnapshot(store,snapshot);let list=await listApplications(store,profileId);assert.equal(list.items.length,1);const id=list.items[0].id;assert.equal(list.items[0].application.appliedAt,null);await store.updateJobState({profileId,offerId:id,changes:{applied:false}});await importSnapshot(store,snapshot);assert.equal((await listApplications(store,profileId)).items.length,0);assert.equal((await applicationDetail(store,profileId,id)).events.length,2);});
test('manual evaluation queue carries immutable offer, commits only validated results and does not touch application data',async t=>{const {store,client,profileId}=await setup(t);const saved=await add(store,profileId);const before=await applicationDetail(store,profileId,saved.offerId);await store.evaluateOffer({profileId,offerId:saved.offerId});await assert.rejects(opportunityRequest(store,'POST','/api/applications',{action:'description',profileId,offerId:saved.offerId,raw_description:'Changed'}),e=>e.status===409);const run=await store.claim();assert.equal(run.options.evaluationOffer.id,saved.offerId);await assert.rejects(store.finish({...run,status:'done',result:{found:1,evaluated:1,saved:1,errors:[],evaluation:{...evaluation,score:0}}}));assert.equal((await store.workerStatus(run.id,run.token)).status,'running');await store.finish({...run,status:'done',result:{found:1,evaluated:1,saved:1,errors:[],evaluation}});const after=await applicationDetail(store,profileId,saved.offerId);assert.deepEqual(after.application,before.application);assert.deepEqual(after.events,before.events);assert.deepEqual(after.evaluation,evaluation);const page=await opportunityHistory(store,historyQuery('/api/jobs?view=paged'));assert.equal(decodeJobRows(page.rows).jobs[0].evaluation.score,85);await assert.rejects(store.evaluateOffer({profileId,offerId:saved.offerId}),e=>e.status===409);});
test('external URL import persists a complete snapshot without evaluating, then queues evaluation on request',async t=>{const {store,profileId}=await setup(t);let evaluations=0;const evaluateOffer=store.evaluateOffer.bind(store);store.evaluateOffer=async input=>{evaluations++;return evaluateOffer(input);};const importedOffer={...offer,title:'Python Developer (Senior)',company:'Firma s.r.o.',location:'Brno',salary_raw:'70 000 - 80 000 CZK monthly',raw_description:'Full description snapshot from the imported posting.',url:'https://example.com/job'};const imported=await opportunityRequest(store,'POST','/api/applications',{action:'import',profileId,url:importedOffer.url},{preview:async()=>({offer:importedOffer,notice:'Imported'})});assert.equal(imported.saved,true);assert.equal(imported.duplicate,false);assert.equal(imported.offer.raw_description,importedOffer.raw_description);assert.equal(imported.offer.canonical_id,canonicalId(importedOffer.company,importedOffer.title,importedOffer.location));assert.equal(evaluations,0);const detail=await applicationDetail(store,profileId,imported.offerId);assert.equal(detail.evaluation,null);assert.equal(detail.offer.raw_description,importedOffer.raw_description);const queued=await opportunityRequest(store,'POST','/api/applications',{action:'evaluate',profileId,offerId:imported.offerId},{dispatch:async()=>({dispatch:'scheduled'})});assert.equal(evaluations,1);assert.equal(queued.status,'queued');const run=await store.claim();assert.equal(run.options.evaluationOffer.canonical_id,imported.offer.canonical_id);});
test('cancelled evaluation cannot save late result',async t=>{const {store,profileId}=await setup(t);const saved=await add(store,profileId);await store.evaluateOffer({profileId,offerId:saved.offerId});const run=await store.claim();await store.stop();await store.finish({...run,status:'done',result:{found:1,evaluated:1,saved:1,errors:[],evaluation}});assert.equal((await applicationDetail(store,profileId,saved.offerId)).evaluation,null);});
test('import preview uses JobPosting without AI and falls back to manual fields on unavailable sites',async()=>{const html='<script type="application/ld+json">'+JSON.stringify({'@graph':[{'@type':'JobPosting',title:'Analytik',hiringOrganization:{name:'Firma'},description:'<p>Práce &amp; procesy</p>',jobLocation:{address:{addressLocality:'Brno'}}}]})+'</script>';const result=await previewOffer('https://example.com/job',{resolver:async()=>[{address:'93.184.216.34',family:4}],transport:async()=>({html})});assert.equal(result.offer.company,'Firma');assert.equal(result.offer.raw_description,'Práce & procesy');const failed=await previewOffer('https://example.com/job',{resolver:async()=>{throw new Error('Secret transport error')}});assert.equal(failed.offer.title,'');assert.ok(!JSON.stringify(failed).includes('Secret'));});
test('HTML import fallback extracts a job description, location and salary without JSON-LD',async()=>{const html='<html><head><meta property="og:title" content="Automation Specialist | Example Labs"><title>Jobs</title></head><body><nav>Navigation</nav><main><h1>Automation Specialist</h1><p class="job-location">Brno</p><p>'+('Build automation workflows and improve business processes. '.repeat(4))+' Pay 70 000 - 80 000 CZK monthly.</p><script>ignore()</script><style>.x{}</style></main></body></html>';const result=await previewOffer('https://example.com/job',{resolver:async()=>[{address:'93.184.216.34',family:4}],transport:async()=>({html})});assert.equal(result.offer.title,'Automation Specialist');assert.equal(result.offer.company,'Example Labs');assert.equal(result.offer.location,'Brno');assert.match(result.offer.salary_raw,/70 000 - 80 000 CZK/);assert.match(result.offer.raw_description,/Build automation workflows/);assert.doesNotMatch(result.offer.raw_description,/ignore|Navigation/);});
test('HTML import keeps extracted text and asks for manual company when no company can be parsed',async()=>{const html='<article><h1>Data Analyst</h1><p>'+('Analyze data and prepare reports. '.repeat(4))+'</p></article>';const result=await previewOffer('https://example.com/job',{resolver:async()=>[{address:'93.184.216.34',family:4}],transport:async()=>({html})});assert.equal(result.offer.title,'');assert.equal(result.offer.company,'');assert.match(result.offer.raw_description,/Analyze data/);assert.match(result.notice,/Doplň ji ručně/);});
test('client-rendered Notino shell is not saved as a fake job description or location',async t=>{const html='<html><head><meta property="og:title" content="Detail pozice | Notino"><title>Detail pozice | Notino</title></head><body><nav>Proč Notino Volné pozice Kontakty EN</nav><div id="vacancy-detail" data-widget="main-cs"></div></body></html>';const result=await previewOffer('https://notino.jobs.cz/detail-pozice?id=2001374025',{resolver:async()=>[{address:'93.184.216.34',family:4}],transport:async()=>({html})});assert.equal(result.offer.title,'');assert.equal(result.offer.company,'Notino');assert.equal(result.offer.location,'');assert.equal(result.offer.raw_description,'');assert.match(result.notice,/JavaScriptu/);const {store,profileId}=await setup(t);const imported=await opportunityRequest(store,'POST','/api/applications',{action:'import',profileId,url:result.offer.url},{preview:async()=>result});assert.equal(imported.saved,false);const page=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&collection=manual'));assert.equal(page.total,0);});
test('Notino LMC pages import the client-loaded job body through the validated public API',async()=>{const url='https://notino.jobs.cz/detail-pozice?id=2001374025&rps=20';const html='<html><head><title>Detail pozice | Notino</title><script src="/assets/js/script.min.js?av=test"></script></head><body><div id="vacancy-detail"></div></body></html>';const fullText='<p>Analyze the fulfillment process and improve operational quality.</p>'.repeat(5);const requests=[];const result=await previewOffer(url,{resolver:async()=>[{address:'93.184.216.34',family:4}],transport:async()=>({html}),fetchResource:async(resource,options)=>{requests.push({url:resource,options});if(resource.includes('script.min.js'))return '"main-cs":{"id":"widget-1","apiKey":"abc123"}';assert.equal(resource,'https://api.capybara.lmc.cz/api/graphql/widget');assert.equal(options.method,'POST');const payload=JSON.parse(options.body);assert.equal(payload.variables.widgetId,'widget-1');assert.equal(payload.variables.jobAdId,'2001374025');assert.equal(payload.variables.rps,20);return JSON.stringify({data:{widget:{jobAd:{title:'Process Improvement Specialist',content:{htmlContent:fullText},employer:{companyName:'Notino s.r.o.'},locations:[{city:'Rajhrad',region:'Jihomoravský',country:'Česká republika'}],salary:{}}}}});}});assert.equal(requests.length,2);assert.equal(result.offer.title,'Process Improvement Specialist');assert.equal(result.offer.company,'Notino s.r.o.');assert.match(result.offer.location,/Rajhrad/);assert.match(result.offer.raw_description,/Analyze the fulfillment process/);assert.ok(result.offer.raw_description.length>300);});
test('SSRF protection refuses private, mapped and redirect destinations before transport',async()=>{for(const addr of ['127.0.0.1','10.2.3.4','169.254.169.254','172.16.1.1','192.168.1.1','::1','::ffff:127.0.0.1','fe80::1','2002:7f00:1::'])assert.equal(publicAddress(addr),false,addr);let calls=0;const transport=async()=>{calls++;return {redirect:'https://127.0.0.1/internal'};};await previewOffer('https://127.0.0.1/',{transport});assert.equal(calls,0);await previewOffer('https://example.com/',{resolver:async()=>[{address:'93.184.216.34',family:4}],transport});assert.equal(calls,1);await assert.rejects(previewOffer('file:///etc/passwd'));await assert.rejects(previewOffer('https://user:pass@example.com'));});
test('summary excludes completed, closed and cancelled events; calendar carries alarm and escaped text',()=>{const active={id:'one',offer:{title:'Analyst',company:'Firma'},application:{...blankApplication(),tasks:[{id:'t',text:'Call',due:'2026-10-09',done:false},{id:'done',text:'Done',due:null,done:true}],interviews:[{id:'i',at:'2026-10-12T10:00:00Z',duration:60,place:'Online',note:'One; Two, three',cancelled:false},{id:'cancel',at:'2026-10-13T10:00:00Z',cancelled:true}]}};const summary=applicationSummary([active,{...active,id:'closed',application:{...active.application,status:'rejected'}}],new Date('2026-10-09T10:00:00Z'));assert.equal(summary.waiting,1);assert.equal(summary.tasks.length,1);assert.equal(summary.interviews.length,1);const ics=interviewCalendar(active.application.interviews[0],active.offer);assert.ok(ics.includes('TRIGGER:-PT30M'));assert.ok(ics.includes('DTSTART:20261012T100000Z'));assert.ok(ics.includes('One\\; Two\\, three'));});

test('HTTPS transport pins validated DNS for Node single-address and auto-family lookups',async t=>{
  const html='<script type="application/ld+json">'+JSON.stringify({'@type':'JobPosting',title:'Analyst',hiringOrganization:{name:'Example'},description:'Text'})+'</script>';
  t.mock.method(https,'get',(url,options,callback)=>{
    options.lookup('example.com',{all:true},(error,addresses)=>{assert.equal(error,null);assert.deepEqual(addresses,[{address:'93.184.216.34',family:4}]);});
    options.lookup('example.com',{},(error,address,family)=>{assert.equal(error,null);assert.equal(address,'93.184.216.34');assert.equal(family,4);});
    const request=new EventEmitter();request.destroy=error=>request.emit('error',error);
    queueMicrotask(()=>{const response=Readable.from([Buffer.from(html)]);response.statusCode=200;response.headers={'content-type':'text/html; charset=utf-8'};callback(response);});
    return request;
  });
  const result=await previewOffer('https://example.com/job',{resolver:async()=>[{address:'93.184.216.34',family:4}]});
  assert.equal(result.offer.title,'Analyst');
});

test('unscored and evaluated offers share pagination, date and verdict filters without null errors',async t=>{
  const {store,profileId}=await setup(t);
  const saved=await add(store,profileId,false);
  const matching=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&verdict=STRONG_FIT'));assert.equal(matching.total,0);
  const newer=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&since=2026-10-08T00:00:00Z'));assert.equal(newer.total,1);
  const older=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&since=2026-10-10T00:00:00Z'));assert.equal(older.total,0);
  for(let i=0;i<14;i++)await addOffer(store,{profileId,offer:{...offer,title:'Position '+i,url:'https://example.com/'+i},applied:false});
  await importSnapshot(store,{name:'Mine',content,rows:[{offer_id:'evaluated',offer:JSON.stringify({...offer,id:'evaluated',title:'Evaluated role',url:'https://example.com/evaluated'}),evaluation:JSON.stringify(evaluation),evaluated_at:'2026-10-01T10:00:00Z'}]});
  await store.updateJobState({profileId,offerId:'evaluated',changes:{saved:true}});
  const page1=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&pageSize=6&collection=saved'));
  const page2=await opportunityHistory(store,historyQuery('/api/jobs?view=paged&pageSize=6&collection=saved&page=2'));
  assert.equal(page1.total,16);assert.equal(page1.counts.STRONG_FIT,1);assert.equal(page1.pageCount,3);assert.equal(new Set([...page1.rows,...page2.rows].map(row=>row.offer_id)).size,12);
  assert.equal(decodeJobRows(page1.rows).invalidCount,0);
});

test('canonical identity matches the backend fingerprint format',()=>assert.equal(canonicalId('Firma s.r.o.','Python Developer (Senior)','Brno'),'job-v1-8393a75a3b97c51630324e554106c740f15774c43c7e3b3394df2c5049fb7091'));
